### ISSUE TITLE
Aynı Repository üzerinde farklı zamanlarda çalışma,

### ISSUE THREAD

**Issue by selcuk-yilmaz** [marcus-clarusway/git-session-3#10]
Farklı zamanlarda  aynı repository üzerinde farklı file ile  çalışmak nasıl olacak? İşlem basamakları nedir? Örneğin python repository 'ye deneme dosyasını gönderdim, x adında başka bir çalışmamı nasıl gönderirim.

**Comment by yaserdemet** [comment]
repoyu locale clonladığınızda silmediğiniz sürece duracaktır. Python reponun içine gelip editör ile dosyanızı ekleyip, tekrar push edebilirsiniz.
