### ISSUE TITLE
git bash

### ISSUE THREAD

**Issue by Selman-S** [marcus-clarusway/git-session-3#2]

**Comment by senosmantuna** [comment]
burası hocanın yazdığı yer mi?

**Comment by FatihG34** [comment]
evet 
hocanın açtığı Issues kısmı

**Comment by senosmantuna** [comment]
teşekkürler

**Comment by betul-kaplan** [comment]
Arkadaşlar, soruları olanlar buradan yazacaklar ki problemlerimizi bilen arkadaşlarımız çözsünler.

**Comment by erhankorkut16** [comment]
açılan issiu nasıl çözüldü yapıyorduk

**Comment by Ozkum** [comment]
> açılan issiu nasıl çözüldü yapıyorduk

kim açtıysa ona comment kısmında çıkıyor, bu issue yi açan arkadaş sanıyorum kapatabilir.
