### ISSUE TITLE
Token kaybettik diyelim yeniden token nerden oluşturuyorduk?

### ISSUE THREAD

**Issue by MuazV** [marcus-clarusway/git-session-3#6]

**Comment by firatolcum** [comment]
Sağ üstte profil fotoğrafınızın yanındaki ok tuşuna basın, Settings sekmesine tıklayın, açılan sayfada sol en altta developer settings ekmesine tılayın , son olarak  solda bulunan personel access tokens sekmesine tıkayın ve Generate new token seçeneğine tıklayın...

**Comment by MuazV** [comment]
teşekkür ederim :)
